version: 2
updates:
  - package-ecosystem: "github-actions"  # zizmor: ignore[dependabot-cooldown]
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-patch" ]
    cooldown:
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 7
      default-days: 7
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all:
        patterns:
          - "*"
    cooldown:
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 7
      default-days: 7
